<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BatDongSanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bat_dong_sans')->insert([
            [
                'tieu_de' => 'Căn hộ view sông Hàn Hải Châu',
                'mo_ta' => 'Căn hộ view sông Hàn, nội thất đầy đủ, an ninh 24/7.',
                'gia' => 5000000000,
                'dien_tich' => 100,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 1,
                'dia_chi_id' => 1,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà phố mặt tiền Sơn Trà',
                'mo_ta' => 'Nhà phố 3 tầng, vị trí vàng, gần biển Mỹ Khê.',
                'gia' => 8000000000,
                'dien_tich' => 150,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 2,
                'dia_chi_id' => 2,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đất nền Liên Chiểu sổ đỏ',
                'mo_ta' => 'Đất nền sổ đỏ, gần khu công nghiệp, tiện kinh doanh.',
                'gia' => 2000000000,
                'dien_tich' => 200,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 3,
                'dia_chi_id' => 4,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư cao cấp Thanh Khê',
                'mo_ta' => 'Chung cư tiện ích đầy đủ, an ninh 24/7, gần trung tâm.',
                'gia' => 3000000000,
                'dien_tich' => 80,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 4,
                'dia_chi_id' => 3,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa biển Mỹ Khê Ngũ Hành Sơn',
                'mo_ta' => 'Villa 5 sao, hồ bơi, sân vườn rộng, view biển tuyệt đẹp.',
                'gia' => 15000000000,
                'dien_tich' => 300,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 1,
                'dia_chi_id' => 5,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Vườn biệt thự Cẩm Lệ',
                'mo_ta' => 'Dự án vườn biệt thự cây xanh, không khí sạch.',
                'gia' => 4500000000,
                'dien_tich' => 180,
                'loai_id' => 3,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 2,
                'dia_chi_id' => 6,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 2,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Kho xưởng cho thuê Liên Chiểu',
                'mo_ta' => 'Kho xưởng hiện đại, tiện cho logistics.',
                'gia' => 1500000000,
                'dien_tich' => 500,
                'loai_id' => 5,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 3,
                'dia_chi_id' => 4,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // NEW 7 PROPERTIES
            [
                'tieu_de' => 'Căn hộ Studio The Monarchy Hải Châu',
                'mo_ta' => 'Căn hộ Studio full nội thất sang trọng, view pháo hoa trực diện sông Hàn. Tiện ích hồ bơi, gym đầy đủ.',
                'gia' => 3500000000,
                'dien_tich' => 55,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 1,
                'dia_chi_id' => 7,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà mặt phố An Hải Tây tiện kinh doanh',
                'mo_ta' => 'Nhà mặt tiền Trần Hưng Đạo, ngay sát cầu Rồng, lưu lượng khách du lịch đông, rất thích hợp kinh doanh nhà hàng, cafe.',
                'gia' => 18000000000,
                'dien_tich' => 120,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 2,
                'dia_chi_id' => 8,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà riêng Mỹ An cách biển 500m',
                'mo_ta' => 'Nhà 2 tầng xây mới 100%, thiết kế phong cách Địa Trung Hải, đi bộ ra bãi biển Mỹ Khê chỉ 5 phút.',
                'gia' => 6500000000,
                'dien_tich' => 85,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 3,
                'dia_chi_id' => 9,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Lô góc Đất nền Eco Charm Liên Chiểu',
                'mo_ta' => 'Lô góc 2 mặt tiền khu đô thị sinh thái Eco Charm, hạ tầng hoàn thiện 100%, có công viên nội khu.',
                'gia' => 4200000000,
                'dien_tich' => 150,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 4,
                'dia_chi_id' => 10,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Văn phòng hạng A Nguyễn Tất Thành',
                'mo_ta' => 'Mặt bằng văn phòng siêu rộng view trực diện biển Vịnh Đà Nẵng, thích hợp làm trụ sở công ty.',
                'gia' => 30000000,
                'dien_tich' => 200,
                'loai_id' => 6,
                'trang_thai_id' => 4, // Cho thuê
                'moi_gioi_id' => 1,
                'dia_chi_id' => 11,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Trang trại sinh thái Hòa Khương',
                'mo_ta' => 'Trang trại quy mô lớn 5 hecta, có sẵn hệ thống tưới tiêu, nhà lưới, ao cá, cách trung tâm TP chỉ 30 phút.',
                'gia' => 12000000000,
                'dien_tich' => 50000,
                'loai_id' => 8, // Trang trại
                'trang_thai_id' => 2,
                'moi_gioi_id' => 2,
                'dia_chi_id' => 12,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Cửa hàng mặt tiền Nguyễn Văn Linh',
                'mo_ta' => 'Mặt bằng kinh doanh trung tâm tài chính Nguyễn Văn Linh, diện tích rộng rãi, chỗ để xe thoải mái.',
                'gia' => 45000000,
                'dien_tich' => 90,
                'loai_id' => 7, // Cửa hàng
                'trang_thai_id' => 4, // Cho thuê
                'moi_gioi_id' => 3,
                'dia_chi_id' => 13,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
